<?php

namespace AppBundle\Repository;

/**
 * AltasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AltasRepository extends \Doctrine\ORM\EntityRepository
{
}
