<?php

namespace AppBundle\Repository;

/**
 * AsignadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignadosRepository extends \Doctrine\ORM\EntityRepository
{
}
