<?php

namespace AppBundle\Repository;

/**
 * EntradaSalidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaSalidaRepository extends \Doctrine\ORM\EntityRepository
{
}
