<?php

namespace AppBundle\Repository;

/**
 * FincasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FincasRepository extends \Doctrine\ORM\EntityRepository
{
}
