<?php

namespace AppBundle\Repository;

/**
 * LineaFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineaFacturaRepository extends \Doctrine\ORM\EntityRepository
{
}
