<?php

namespace AppBundle\Repository;

/**
 * NoLaborablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoLaborablesRepository extends \Doctrine\ORM\EntityRepository
{
}
