<?php

namespace AppBundle\Repository;

/**
 * ParteTrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParteTrabajoRepository extends \Doctrine\ORM\EntityRepository
{
}
