<?php

namespace AppBundle\Repository;

/**
 * PreciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreciosRepository extends \Doctrine\ORM\EntityRepository
{
}
