<?php

namespace AppBundle\Repository;

/**
 * VariedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariedadRepository extends \Doctrine\ORM\EntityRepository
{
}
