<?php

namespace AppBundle\Repository;

/**
 * VencimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VencimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
